# === Configuration Instructions ===
# - Set 'Base_path' to the absolute path where your data is stored.
# - 'Data_folder' should be the name of the main directory containing your data.
# - 'Name_of_folder_one' and 'Name_of_folder_two' should be subdirectories inside 'Data_folder'.

Base_path: "/absolute/path/to/your/data"
Data_folder: "Illumina_C6"
Name_of_folder_one: "dehosted"
Name_of_folder_two: "no_dehost"

Packages: #packages needed to run the SIGNAL comparison script
  - dplyr
  - data.table
  - readxl
  - tidyverse
  - stringr
  - R.utils
  - writexl
  - lubridate
  - stringi
  - ggplot2
  - gridExtra
  - tinytex
  - kableExtra
  - DT
  - extraoperators
  - hablar
  - ape
  - phylogram
  - dendextend
  - data.tree
  - here
