# === Configuration Instructions ===
# - Set 'Base_path' to the absolute path where your data is stored
#   - Ex. /Path/To/Overall_Data
# - 'Name_of_folder_one' and 'Name_of_folder_two' should be subdirectories inside 'Base_path' 

Base_path: "/absolute/path/to/your/data"
Name_of_folder_one: "User1_Results"
Name_of_folder_two: "User2_Results"

# Packages needed to run the SIGNAL comparison script - No need to touch
Packages:
  - dplyr
  - data.table
  - readxl
  - tidyverse
  - stringr
  - R.utils
  - writexl
  - lubridate
  - stringi
  - ggplot2
  - gridExtra
  - tinytex
  - kableExtra
  - DT
  - extraoperators
  - hablar
  - ape
  - phylogram
  - dendextend
  - data.tree
  - here
  - colorspace
